VILLAGERS = "villageois"
WOLVES = "loups-garous"

GAME_START = "🎮 La partie vient de commencer !"
GAME_OVER = "🏆 La partie est terminée ! Les {winner} ont gagné !"
SEER_TURN = "🔮 La voyante va pouvoir espionner un joueur."
WOLVES_TURN = "🐺 Les loups-garous vont décider d'une victime à dévorer."
VOTE_ELIMINATION = "🗳️  Le village a décidé d'éliminer le joueur {target_id} ({role_name})."
NIGHT_START = "🌙 La nuit tombe sur le village de Thiercelieux..."
DAY_NO_DEATH = "☀️  Le village se réveille et personne n'est mort pendant la nuit !"
DEAD_PLAYER = "le joueur {player_id} ({role_name})"
DEAD_PLAYERS_JOIN = "{players} et {last_player}"
DAY_DEATHS = "☀️  Le village se réveille sans... {dead_players}."
HUNTER_SHOT = "🎯 PAN ! Le chasseur tire une dernière balle sur le joueur {target_id} ({role_name})"

STATS_TITLE = "📊 WERWOLF SIMULATION RESULTS"
STATS_FACTION = "Faction"
STATS_WINS = "Wins"
STATS_WIN_RATE = "Win rate"
STATS_GAMES_RUN = "Games run: {n_games}"
