VILLAGERS = "villageois"
WOLVES = "loups-garous"
LOVERS = "amoureux"

GAME_START = "🎮 La partie vient de commencer !"
NIGHT_START = "🌙 La nuit tombe sur le village de Thiercelieux..."
THIEF_TURN = "🦹 Le voleur va pouvoir échanger, ou non, sa carte."
CUPID_TURN = "💘 Cupidon va pouvoir rendre deux personnes amoureuses."
SEER_TURN = "🔮 La voyante va pouvoir espionner un joueur."
WOLVES_TURN = "🐺 Les loups-garous vont décider d'une victime à dévorer."
WITCH_TURN = "🧪 La sorcière va pouvoir utiliser ses potions."
DAY_DEATHS = "☀️  Le village se réveille sans... {dead_players}."
DEAD_PLAYER = "le joueur {player_id} ({role_name})"
DEAD_PLAYERS_JOIN = "{players} et {last_player}"
LOVER_GRIEF = "🪦 Dans un élan de chagrin, le joueur {lover_id} ({role_name}), a décidé de rejoindre le joueur {dead_id} dans sa tombe."
DAY_NO_DEATH = "☀️  Le village se réveille et personne n'est mort pendant la nuit !"
VOTE_ELIMINATION = "🗳️  Le village a décidé d'éliminer le joueur {target_id} ({role_name})."
HUNTER_SHOT = "🎯 PAN ! Le chasseur a décidé d'exécuter le joueur {target_id} ({role_name})."
HUNTER_NO_SHOT = "🎯 Par sa toute bonté, le chasseur n'a finalement exécuté personne."
GAME_OVER = "🏆 La partie est terminée ! Les {winner} ont gagné !"

STATS_TITLE = "📊 WERWOLF SIMULATION RESULTS"
STATS_FACTION = "Faction"
STATS_WINS = "Wins"
STATS_WIN_RATE = "Win rate"
STATS_GAMES_RUN = "Games run: {n_games}"
