ROLE_COUNTS = {
    "thief": 1,
    "cupid": 1,
    "seer": 1,
    "wolf": 3,
    "little_girl": 1,
    "witch": 1,
    "villager": 4,
    "hunter": 1
}

ALPHA = 0.15
VOTE_NOISE = 0.2 
GRUDGE_IMMEDIATE_WEIGHT = 0.5
CO_VOTE_BETA = 0.3
CO_VOTE_ASSOCIATION_THRESHOLD = 0.6
CO_VOTE_ASSOCIATION_WEIGHT = 0.4
CONVINCE_ROLE_VALUE_WEIGHT = 0.1
SUSPICION_ROLE_VALUE_WEIGHT = 0.1
HUNTER_SHOT_THRESHOLD = 0.5
WITCH_KILL_THRESHOLD = 0.5
USE_SHERIFF = 1
N_GAMES = 10000
SEED = 42
